### ISSUE TITLE
Using the English dictionary with Maven

### ISSUE THREAD

**Issue by BullyWiiPlaza** [bobbylight/SpellChecker#8]
The example code references the `English` dictionary but the file location is invalid when using `Maven`:
```
private SpellingParser createSpellingParser() {
		File zip = new File("src/main/dist/english_dic.zip");
		try {
			return SpellingParser.createEnglishSpellingParser(zip, true);
		} catch (IOException ioe) {
			ioe.printStackTrace();
		}
		return null;
	}
```

The file does not exist:
```
java.io.FileNotFoundException: src\main\dist\english_dic.zip (The system cannot find the path specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.fife.ui.rsyntaxtextarea.spell.SpellingParser.createEnglishSpellingParser(SpellingParser.java:178)
	at org.fife.ui.rsyntaxtextarea.spell.demo.DemoRootPane.createSpellingParser(DemoRootPane.java:124)
	at org.fife.ui.rsyntaxtextarea.spell.demo.DemoRootPane.access$100(DemoRootPane.java:37)
	at org.fife.ui.rsyntaxtextarea.spell.demo.DemoRootPane$1.run(DemoRootPane.java:74)
```

How do you use a built-in dictionary? Is it even bundled or are you supposed to always provide your own in case you're not running this project from source?

**Comment by bobbylight** [comment]
Yes, it's bundled, see:

https://github.com/bobbylight/SpellChecker/tree/master/src/main/dist

For the example to work you need to ensure you run from the project's root directory, so the relative path works.

I didn't include the English spellings in the project jar itself, and expected folks to deliver it as a loose file with their project.  I'm not sure why, perhaps due to concerns over its size?  In any case, it's only 152 KB so it isn't very bulky.  I suppose I could consider shipping it inside the spellchecker jar.  But IMO it's nice for the dictionary files to be external to the code, so users are able to append to/edit/replace the dictionary files if they want to.

**Comment by bobbylight** [comment]
Closing as answered.
